// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oshtjqsnxhtsnjrlhgnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zaHRqcXNueGh0c25qcmxoZ25uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODY5OTcsImV4cCI6MjA2NjM2Mjk5N30.VlB4edxPWd-euJC45t7WkeNfNZgPj1RWKuu_g1PQJTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);